<?xml version="1.0" encoding="UTF-8"?>
<metadata>
     {* stručný název Vašich dat *}
    <name>Analýza propojení uživatelů Flickru na základě klíčových slov</name>
     {* popis dat, odkud jsou, o čem (jaká podmožina), co je uzel a co hrana, přibližný rozsah, *}
    <description>Popis dat - data získaná z Flickr API, uzel - uživatel služby Flickr, hrana - existuje mezi uživateli v případě, že se u fotografií jimi nahranými vyskytují stejná klíčová slova</description>
     {* čas poslední aktualizace *}
    <lastUpdate>{$lastUpdate}</lastUpdate>
     {* interval v minutách jak budete aktualizovat data, např. týden 60*24*7 = 10080 minut *}
    <updateInterval>10080</updateInterval>
     {* seznam autorů = členů týmu, libovolný počet 1-3 *}
    <authors>
         {* jméno nebo username a město odkud pocházíte (nebo oblíbené město), bude použito v dalších cvičeních *}
        <author name="janusjan" city="Malacky" />
        <author name="libaljar" city="Horní Cetno" />
        <author name="venusmar" city="Český Krumlov" />
    </authors>
</metadata>