{block content}

<div id="header">
    <h1>Flickr analyser</h1>

{* <h2>Podnadpis</h2> *}
</div>

<div>

    <p>Analýza propojení uživatelů Flickru na základě klíčových slov.</p>

</div>

<style>
    body {
        margin: 0;
        padding: 0;
    }

    div {
        padding: .2em 1em;
    }

    #header {
        background: #EEE;
        border-bottom: 1px #DDD solid;
    }

    h1 {
        color: #0056ad;
        font-size: 30px;
    }

    h2 {
        color: gray;
        font-size: 20px;
    }

    img {
        border: none;
    }
</style>